# Generated by Django 2.2.6 on 2024-07-03 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0069_auto_20240623_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 3, 12, 35, 16, 181560), null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='news_access',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Доступ к новостям'),
        ),
        migrations.AlterField(
            model_name='user_widgets',
            name='calc',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Калькулятор'),
        ),
        migrations.AlterField(
            model_name='user_widgets',
            name='news',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Новости'),
        ),
        migrations.AlterField(
            model_name='user_widgets',
            name='notes',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Заметки'),
        ),
        migrations.AlterField(
            model_name='user_widgets',
            name='reqs',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Заявки на испытания'),
        ),
        migrations.AlterField(
            model_name='user_widgets',
            name='widgets_order',
            field=models.TextField(blank=True, default='1_2_3_4_5_6_7_8_9_10_11_12', null=True, verbose_name='Порядок виджетов'),
        ),
    ]
