# Generated by Django 2.2.6 on 2024-12-03 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0072_auto_20241203_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 3, 17, 25, 12, 20865), null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='day_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='day_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала'),
        ),
    ]
