# Generated by Django 2.2.6 on 2024-07-03 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0094_auto_20240623_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='pub_day',
            field=models.TextField(default=datetime.date(2024, 7, 3), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='th',
            name='pub_day',
            field=models.TextField(default=datetime.date(2024, 7, 3), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='th',
            name='year',
            field=models.TextField(blank=True, choices=[('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], null=True, verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='pub_day',
            field=models.TextField(default=datetime.date(2024, 7, 3), verbose_name='Дата'),
        ),
    ]
