# Generated by Django 2.2.6 on 2024-07-03 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0130_auto_20240623_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_pass',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 3, 12, 35, 16, 204397), null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='day',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 3, 12, 35, 16, 203393), verbose_name='Дата'),
        ),
    ]
