# Generated by Django 2.2.6 on 2024-11-12 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0131_auto_20240703_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_pass',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 11, 12, 12, 8, 3, 596776), null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='day',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 12, 12, 8, 3, 595791), verbose_name='Дата'),
        ),
    ]
