# Generated by Django 2.2.6 on 2024-12-03 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0132_auto_20241112_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_pass',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 3, 17, 12, 29, 985610), null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='day',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 3, 17, 12, 29, 985610), verbose_name='Дата'),
        ),
    ]
