# Generated by Django 2.2.6 on 2024-12-03 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0133_auto_20241203_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_pass',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 3, 17, 25, 12, 28874), null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='day',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 3, 17, 25, 12, 28874), verbose_name='Дата'),
        ),
    ]
