# Generated by Django 2.2.6 on 2024-07-03 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corresp', '0007_auto_20240623_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corresp',
            options={'ordering': ('-day',), 'verbose_name': 'Корреспонденция', 'verbose_name_plural': 'Корреспонденция'},
        ),
    ]
