# Generated by Django 2.2.6 on 2024-11-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corresp', '0008_auto_20240703_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='who',
            name='who',
            field=models.CharField(max_length=200, verbose_name='автор/адресат'),
        ),
    ]
